// Generated by CoffeeScript 2.5.1
(function() {
  var drawStar, fillIndicator, indicatorCanvas, indicatorContext, inputCanvas, inputContext, paths;

  inputCanvas = document.getElementById("input");

  inputContext = inputCanvas.getContext("2d");

  indicatorCanvas = document.getElementById("indicator");

  indicatorContext = indicatorCanvas.getContext("2d");

  paths = [];

  inputCanvas.addEventListener('click', function(e) {
    var bound, color, i, len, starInfo, x, y;
    bound = inputCanvas.getBoundingClientRect();
    x = e.pageX - bound.left;
    y = e.pageY - bound.top;
    color = 'white';
    for (i = 0, len = paths.length; i < len; i++) {
      starInfo = paths[i];
      if (inputContext.isPointInPath(starInfo.star, x, y)) {
        color = starInfo.color;
      }
    }
    return fillIndicator(color);
  });

  fillIndicator = function(color) {
    indicatorContext.fillStyle = color;
    return indicatorContext.fillRect(0, 0, indicatorCanvas.width, indicatorCanvas.height);
  };

  drawStar = function(centerX, centerY, color = 'black') {
    var drawAngle, i, innerRadius, outerRadius, ref, rotation, spikes, star, step, x, y;
    rotation = (Math.PI / 2) * 3;
    x = centerX;
    y = centerY;
    spikes = 5;
    outerRadius = 60;
    innerRadius = 30;
    step = Math.PI / spikes;
    star = new Path2D();
    star.moveTo(centerX, centerY - outerRadius);
    drawAngle = function() {
      x = centerX + Math.cos(rotation) * outerRadius;
      y = centerY + Math.sin(rotation) * outerRadius;
      star.lineTo(x, y);
      rotation += step;
      x = centerX + Math.cos(rotation) * innerRadius;
      y = centerY + Math.sin(rotation) * innerRadius;
      star.lineTo(x, y);
      return rotation += step;
    };
    for (x = i = 0, ref = spikes; (0 <= ref ? i < ref : i > ref); x = 0 <= ref ? ++i : --i) {
      drawAngle();
    }
    star.lineTo(centerX, centerY - outerRadius);
    star.closePath();
    inputContext.fillStyle = color;
    inputContext.fill(star);
    return {star, color};
  };

  paths.push(drawStar(100, 100, 'red'));

  paths.push(drawStar(500, 100, 'blue'));

  paths.push(drawStar(300, 300, 'green'));

  paths.push(drawStar(100, 500, 'yellow'));

  paths.push(drawStar(500, 500));

}).call(this);
